typography_spectrum: 0.6094462182372808
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.23717835475690663
  lightness: 0.2951409602537751
  saturation: 0.35828008269891143
  rhythmicContrast: 0.804094610735774
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.38333530304953456
analytics:
  google: null
  facebook: null
  twitter: null
name: makenaworld
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: MakenaSinging
description: 'Breathe, Sing, Be Still, Enjoy'
purpose: []
